services:

  api-gateway:
    build: ./api-gateway-impl
    environment:
      SPRING_PROFILES_ACTIVE: "${APPLICATION_PROFILE}"
      AUTH_SERVICE_URL: 'http://auth-service:8080'
      USER_SERVICE_URL: 'http://user-service:8080'
      ORDER_SERVICE_URL: 'http://order-service:8080'
      PAYMENT_SERVICE_URL: 'http://payment-service:8080'
      JAVA_TOOL_OPTIONS: '-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5000'
    ports:
      - '8080:8080'
      - '5000:5000'
    expose:
      - '8080' # application api
      - '5000' # debug
    restart: 'always'
    depends_on:
      - 'auth-service'
      - 'user-service'
      - 'order-service'

  auth-service:
    image: "ghcr.io/${GITHUB_INNOWISE_USERNAME}/${AUTH_SERVICE_GH_REPO_NAME}/${AUTH_SERVICE_IMAGE_NAME}"
    environment:
      SPRING_PROFILES_ACTIVE: "${APPLICATION_PROFILE}"
      DB_URL: "jdbc:postgresql://auth-service-db:5432/${AUTH_SERVICE_DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      GITHUB_INNOWISE_USERNAME: "${GITHUB_INNOWISE_USERNAME}"
      GITHUB_INNOWISE_TOKEN: "${GITHUB_INNOWISE_TOKEN}"
      AUTH_SERVICE_GH_REPO_NAME: "${AUTH_SERVICE_GH_REPO_NAME}"
      AUTH_SERVICE_IMAGE_NAME: "${AUTH_SERVICE_IMAGE_NAME}"
      TOKEN_SECRET: "${TOKEN_SECRET}"
      JAVA_TOOL_OPTIONS: '-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005'
    ports:
#      - '9000:8080'
      - '5005:5005'
    expose:
#      - '9000' # application api
      - '5005' # debug
    restart: 'always'
    depends_on:
      - 'auth-service-db'

  user-service:
    image: "ghcr.io/${GITHUB_INNOWISE_USERNAME}/${USER_SERVICE_GH_REPO_NAME}/${USER_SERVICE_IMAGE_NAME}"
    environment:
      SPRING_PROFILES_ACTIVE: "${APPLICATION_PROFILE}"
      DB_URL: "jdbc:postgresql://user-service-db:5432/${USER_SERVICE_DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      REDIS_HOST: "redis-db"
      REDIS_PORT: '6379'
      GITHUB_INNOWISE_USERNAME: "${GITHUB_INNOWISE_USERNAME}"
      GITHUB_INNOWISE_TOKEN: "${GITHUB_INNOWISE_TOKEN}"
      USER_SERVICE_GH_REPO_NAME: "${USER_SERVICE_GH_REPO_NAME}"
      USER_SERVICE_IMAGE_NAME: "${USER_SERVICE_IMAGE_NAME}"
      TOKEN_SECRET: "${TOKEN_SECRET}"
      JAVA_TOOL_OPTIONS: '-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006'
    ports:
#      - '8090:8080'
      - '5006:5006'
    expose:
#      - '8090' # application api
      - '5006' # debug
    restart: 'always'
    depends_on:
      - 'user-service-db'
      - 'redis-db'

  order-service:
    image: "ghcr.io/${GITHUB_INNOWISE_USERNAME}/${ORDER_SERVICE_GH_REPO_NAME}/${ORDER_SERVICE_IMAGE_NAME}"
    environment:
      SPRING_PROFILES_ACTIVE: "${APPLICATION_PROFILE}"
      DB_URL: "jdbc:postgresql://order-service-db:5432/${ORDER_SERVICE_DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      GITHUB_INNOWISE_USERNAME: "${GITHUB_INNOWISE_USERNAME}"
      GITHUB_INNOWISE_TOKEN: "${GITHUB_INNOWISE_TOKEN}"
      ORDER_SERVICE_GH_REPO_NAME: "${ORDER_SERVICE_GH_REPO_NAME}"
      ORDER_SERVICE_IMAGE_NAME: "${ORDER_SERVICE_IMAGE_NAME}"
      TOKEN_SECRET: "${TOKEN_SECRET}"
      USER_SERVICE_URL: 'http://user-service:8080'
      KAFKA_BOOTSTRAP_URL: "kafka:9092"
      JAVA_TOOL_OPTIONS: '-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5007'
    ports:
#      - '9009:8080'
      - '5007:5007'
    expose:
#      - '9009' # application api
      - '5007' # debug
    restart: 'always'
    depends_on:
      - 'order-service-db'
      - 'kafka'

  payment-service:
    image: "ghcr.io/${GITHUB_INNOWISE_USERNAME}/${PAYMENT_SERVICE_GH_REPO_NAME}/${PAYMENT_SERVICE_IMAGE_NAME}"
    environment:
      SPRING_PROFILES_ACTIVE: "${APPLICATION_PROFILE}"
      MONGO_DB_URL: "mongodb://payment-service-db:27017/${PAYMENT_SERVICE_DB_NAME}"
      GITHUB_INNOWISE_USERNAME: "${GITHUB_INNOWISE_USERNAME}"
      GITHUB_INNOWISE_TOKEN: "${GITHUB_INNOWISE_TOKEN}"
      PAYMENT_SERVICE_GH_REPO_NAME: "${PAYMENT_SERVICE_GH_REPO_NAME}"
      PAYMENT_SERVICE_IMAGE_NAME: "${PAYMENT_SERVICE_IMAGE_NAME}"
      TOKEN_SECRET: "${TOKEN_SECRET}"
      KAFKA_BOOTSTRAP_URL: "kafka:9092"
      JAVA_TOOL_OPTIONS: '-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5008'
    ports:
#      - '9015:8080'
      - '5008:5008'
    expose:
#      - '9015' # application api
      - '5007' # debug
    restart: 'always'
    depends_on:
      - 'payment-service-db'
      - 'kafka'

  auth-service-db:
    image: 'postgres:17-alpine'
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${AUTH_SERVICE_DB_NAME}"
    ports:
      - '7777:5432'
    volumes:
      - 'pg-auth-service-vol:/var/lib/postgresql/data'
    restart: 'always'

  user-service-db:
    image: 'postgres:17-alpine'
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${USER_SERVICE_DB_NAME}"
    ports:
      - '8888:5432'
    volumes:
      - 'pg-user-service-vol:/var/lib/postgresql/data'
    restart: 'always'

  redis-db:
    image: 'redis:7.2.10-alpine'
    ports:
      - '6379:6379'
    volumes:
      - 'redis-user-service-vol:/data'
    restart: 'always'

  order-service-db:
    image: 'postgres:17-alpine'
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${ORDER_SERVICE_DB_NAME}"
    ports:
      - '6666:5432'
    volumes:
      - 'pg-order-service-vol:/var/lib/postgresql/data'
    restart: 'always'

  payment-service-db:
    image: 'mongo:7.0.24-jammy'
    environment:
      MONGO_INITDB_DATABASE: "${PAYMENT_SERVICE_DB_NAME}"
    ports:
      - '27017:27017'
    volumes:
      - 'mongo-payment-service-vol:/data/db'
    restart: 'always'

  kafka:
    image: 'confluentinc/cp-kafka:7.9.3'
    environment:
      KAFKA_NODE_ID: '1'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'

      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,PLAINTEXT_LOCALHOST://0.0.0.0:29092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092,PLAINTEXT_LOCALHOST://localhost:29092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,PLAINTEXT_LOCALHOST:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'

      KAFKA_LOG_DIRS: '/var/lib/kafka/data'

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: '1'
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: '1'

      CLUSTER_ID: "${KAFKA_CLUSTER_ID}"

    ports:
      - "29092:29092"
    volumes:
      - 'kafka-data-vol:/var/lib/kafka/data'


volumes:
  pg-auth-service-vol:
  pg-user-service-vol:
  pg-order-service-vol:
  redis-user-service-vol:
  mongo-payment-service-vol:
  kafka-data-vol:
