spring:
  application:
    name: 'api-gateway-service'

  profiles:
    active: "${APPLICATION_PROFILE}"

management:
  endpoints:
    web:
      exposure:
        include: 'health,info'
  endpoint:
    health:
      probes:
        enabled: 'true'
  health:
    livenessState:
      enabled: 'true'
    readinessState:
      enabled: 'true'

application:
  gateway:
    services:
      user-service: "${USER_SERVICE_URL}"
      auth-service: "${AUTH_SERVICE_URL}"
      order-service: "${ORDER_SERVICE_URL}"
      payment-service: "${PAYMENT_SERVICE_URL}"
